import { NextRequest, NextResponse } from 'next/server'
import { createServerClient } from '@/lib/supabase/server'
import { getSessionUser, hasPermission } from '@/lib/auth/permissions'

export async function GET(req: NextRequest) {
  const user = await getSessionUser()
  if (!user) return NextResponse.json({ error: 'Não autenticado' }, { status: 401 })
  if (!hasPermission(user.role, 'view_orders_dashboard')) {
    return NextResponse.json({ error: 'Sem permissão' }, { status: 403 })
  }

  const { searchParams } = new URL(req.url)
  const status = searchParams.get('status')
  const from = searchParams.get('from')
  const to = searchParams.get('to')

  const supabase = createServerClient()
  let query = supabase
    .from('orders')
    .select(`
      *,
      creator:users!orders_created_by_fkey(id, name),
      items:order_items(
        *,
        product:products(id, name, sku, photo_url, type)
      )
    `)
    .order('created_at', { ascending: false })

  if (status && status !== 'todos') {
    query = query.eq('status', status)
  }
  if (from) query = query.gte('created_at', from)
  if (to) query = query.lte('created_at', `${to}T23:59:59`)

  const { data, error } = await query

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json(data)
}

export async function POST(req: NextRequest) {
  const user = await getSessionUser()
  if (!user) return NextResponse.json({ error: 'Não autenticado' }, { status: 401 })
  if (!hasPermission(user.role, 'manage_orders')) {
    return NextResponse.json({ error: 'Sem permissão' }, { status: 403 })
  }

  const body = await req.json()
  const { items } = body

  if (!items || !Array.isArray(items) || items.length === 0) {
    return NextResponse.json({ error: 'Pedido deve ter ao menos 1 item' }, { status: 400 })
  }

  for (const item of items) {
    if (!item.product_id || !item.quantity || item.quantity <= 0) {
      return NextResponse.json({ error: 'Cada item deve ter produto e quantidade > 0' }, { status: 400 })
    }
  }

  const supabase = createServerClient()

  // Create order (code generated by trigger)
  const { data: order, error: orderError } = await supabase
    .from('orders')
    .insert({ created_by: user.id, code: '' })
    .select()
    .single()

  if (orderError) return NextResponse.json({ error: orderError.message }, { status: 500 })

  // Create order items
  const orderItems = items.map((item: any) => ({
    order_id: order.id,
    product_id: item.product_id,
    quantity: item.quantity,
    priority: item.priority || 'normal',
  }))

  const { error: itemsError } = await supabase
    .from('order_items')
    .insert(orderItems)

  if (itemsError) {
    await supabase.from('orders').delete().eq('id', order.id)
    return NextResponse.json({ error: itemsError.message }, { status: 500 })
  }

  // Fetch complete order
  const { data: fullOrder } = await supabase
    .from('orders')
    .select(`
      *,
      items:order_items(
        *,
        product:products(id, name, sku, photo_url, type)
      )
    `)
    .eq('id', order.id)
    .single()

  return NextResponse.json(fullOrder, { status: 201 })
}
